// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGxc-NcZV07Luql-EbLO3g2cqEAqFMhkA',
    appId: '1:246785749201:web:70a0f46e7b65afab2b55f0',
    messagingSenderId: '246785749201',
    projectId: 'roamwise-f3917',
    authDomain: 'roamwise-f3917.firebaseapp.com',
    storageBucket: 'roamwise-f3917.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPKsqQNGZSDJQpiukmjOXxt4nL0N1r3l8',
    appId: '1:246785749201:android:f315c78ff0e868252b55f0',
    messagingSenderId: '246785749201',
    projectId: 'roamwise-f3917',
    storageBucket: 'roamwise-f3917.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmtogeTHu3rzUH1TeWVHQWv_G2s2KsxO4',
    appId: '1:246785749201:ios:6e9f56ecd2a8f9df2b55f0',
    messagingSenderId: '246785749201',
    projectId: 'roamwise-f3917',
    storageBucket: 'roamwise-f3917.firebasestorage.app',
    iosBundleId: 'com.example.roamwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmtogeTHu3rzUH1TeWVHQWv_G2s2KsxO4',
    appId: '1:246785749201:ios:6e9f56ecd2a8f9df2b55f0',
    messagingSenderId: '246785749201',
    projectId: 'roamwise-f3917',
    storageBucket: 'roamwise-f3917.firebasestorage.app',
    iosBundleId: 'com.example.roamwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAGxc-NcZV07Luql-EbLO3g2cqEAqFMhkA',
    appId: '1:246785749201:web:bcc1cd609d1b83312b55f0',
    messagingSenderId: '246785749201',
    projectId: 'roamwise-f3917',
    authDomain: 'roamwise-f3917.firebaseapp.com',
    storageBucket: 'roamwise-f3917.firebasestorage.app',
  );
}
